version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"  # 从 daily 改为 monthly
    open-pull-requests-limit: 3  # 限制同时打开的 PR 数量
    ignore:
      - dependency-name: "*"  # 忽略所有依赖
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]